name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12.x
         
    #Instalar as dependencias NPM/Yarn
    - name: Install dependecies
      run: yarn
    
    #Gerar a build
    - name: Run build
      run: yarn build
    
    #Copiar pra dentro da Digital Ocean
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/app/go-barber"

    #Executar "yarn" na Digital Oceacn
    #Executar as migrations do TypeORM
    # Restart no servidor
    
      
